CREATE TABLE IF NOT EXISTS "users" (
	"id" SERIAL PRIMARY KEY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	"email" VARCHAR(50) NOT NULL UNIQUE,
	"password" VARCHAR(50) NOT NULL,
	"age" INTEGER NOT NULL,
	"profile_picture" VARCHAR(100),
	"admin" BOOLEAN DEFAULT FALSE NOT NULL,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"last_login" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "diaries" (
	"id" SERIAL PRIMARY KEY,
	"title" VARCHAR(100) NOT NULL,
	"content" TEXT,
	"user_id" INTEGER REFERENCES "users" ("id") ON DELETE CASCADE,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);